### ISSUE TITLE
IDE Internal ERROR: Intention Description Dir URL is null: Auto fill call parameters; AutoFillCallArguments/src/main/resources/intentionDescriptions/AutoFillCallArguments; while looking for description.html [Plugin: de.kontext_e.idea.plugins.autofill]

### ISSUE THREAD

**Issue by xiaoyan94** [kontext-e/AutoFillingCallArguments#9]
```
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Auto fill call parameters; AutoFillCallArguments/src/main/resources/intentionDescriptions/AutoFillCallArguments; while looking for description.html [Plugin: de.kontext_e.idea.plugins.autofill]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:62)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:132)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.kt:84)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$0(SearchableOptionsRegistrarImpl.java:137)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:61)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:137)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.getAcceptableDescriptions(SearchableOptionsRegistrarImpl.java:464)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$optionsFlow$1.invokeSuspend(ActionAsyncProvider.kt:284)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$optionsFlow$1.invoke(ActionAsyncProvider.kt)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$optionsFlow$1.invoke(ActionAsyncProvider.kt)
	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:320)
	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Builders.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

**Comment by WilliamThimm** [comment]
Thank you for reporting this.
This should be fixed now with version 1.3.1
